spring.application.name=WorkOrderService

server.port=8080
spring.profiles.active=dev


# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/workorder_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Enable Spring Security debug logging (prints filter chain and auth decisions)
spring.security.debug=true
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web=DEBUG

# JWT Configuration
jwt.secret=MySecretKeyForJWTTokenGenerationAndValidation12345678901234567890

spring.devtools.restart.enabled=true
spring.devtools.remote.secret=my-secret-key 
spring.devtools.remote.enabled=true